<?php

namespace Database\Seeders;

use App\Models\Lang;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class LangSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $langs = [
            '1C' => '1c',
            'ABNF' => 'abnf',
            'Access logs' => 'accesslog',
            'Ada' => 'ada',
            'Arduino (C++ w/Arduino libs)' => 'arduino',
            'ARM assembler' => 'armasm',
            'AVR assembler' => 'avrasm',
            'ActionScript' => 'actionscript',
            'AngelScript' => 'angelscript',
            'Apache' => 'apache',
            'AppleScript' => 'applescript',
            'Arcade' => 'arcade',
            'AsciiDoc' => 'asciidoc',
            'AspectJ' => 'aspectj',
            'AutoHotkey' => 'autohotkey',
            'AutoIt' => 'autoit',
            'Awk' => 'awk',
            'Bash' => 'bash',
            'Basic' => 'basic',
            'BNF' => 'bnf',
            'Brainfuck' => 'brainfuck',
            'C#' => 'csharp',
            'C' => 'c',
            'C++' => 'cpp',
            'C/AL' => 'cal',
            'Cache Object Script' => 'cos',
            'CMake' => 'cmake',
            'Coq' => 'coq',
            'CSP' => 'csp',
            'CSS' => 'css',
            'Chaos' => 'chaos',
            'Cypher (Neo4j)' => 'cypher',
            'D' => 'd',
            'DNS Zone file' => 'dns',
            'DTS (Device Tree)' => 'dts',
            'Glimmer and EmberJS' => 'hbs',
            'GN for Ninja' => 'gn',
            'Go' => 'go',
            'Grammatical Framework' => 'gf',
            'High-level shader language' => 'hlsl',
            'LiveCode Server' => 'livecodeserver',
            'Maya Embedded Language' => 'mel',
            'mIRC Scripting Language' => 'mirc',
            'Object Constraint Language' => 'ocl',
            'Objective C' => 'objectivec',
            'OpenGL Shading Language' => 'glsl',
            'Oracle Rules Language' => 'ruleslanguage',
            'PostgreSQL & PL/pgSQL' => 'pgsql',
            'Protocol Buffers' => 'protobuf',
            'Python profiler results' => 'profile',
            'Python REPL' => 'python-repl',
            'Razor CSHTML' => 'cshtml',
            'Rebol & Red' => 'redbol',
            'x86 Assembly' => 'x86asm',
            'Zephir' => 'zephir',
            'Unicorn Rails log' => 'unicorn-rails-log',
            'Terraform (HCL)' => 'terraform',
            'Test Anything Protocol' => 'tap',
            'Structured Text' => 'iecst',
            'Shape Expressions' => 'shexc',
            'STEP Part 21' => 'p21',
            'Robot Framework' => 'robot',
            'RPM spec files' => 'rpm-specfile',
            'RenderMan RIB' => 'rib',
            'RenderMan RSL' => 'rsl',
            "Cap’n Proto" => 'capnproto',
            'Clojure' => 'clojure',
            'CoffeeScript' => 'coffeescript',
            'CpcdosC+' => 'cpc',
            'Crmsh' => 'crmsh',
            'Crystal' => 'crystal',
            'cURL' => 'curl',
            'Dafny' => 'dafny',
            'Dart' => 'dart',
            'Delphi' => 'dpr',
            'Diff' => 'diff',
            'Django' => 'django',
            'Dockerfile' => 'dockerfile',
            'DOS' => 'dos',
            'dsconfig' => 'dsconfig',
            'Dust' => 'dust',
            'Dylan' => 'dylan',
            'EBNF' => 'ebnf',
            'Elixir' => 'elixir',
            'Elm' => 'elm',
            'Erlang' => 'erlang',
            'Excel' => 'excel',
            'Extempore' => 'extempore',
            'F#' => 'fsharp',
            'FIX' => 'fix',
            'Fortran' => 'fortran',
            'G-Code' => 'gcode',
            'Gams' => 'gams',
            'GAUSS' => 'gauss',
            'GDScript' => 'godot',
            'Gherkin' => 'gherkin',
            'Golo' => 'golo',
            'Gradle' => 'gradle',
            'GraphQL' => 'graphql',
            'Groovy' => 'groovy',
            'GSQL' => 'gsql',
            'HTML' => 'html',
            'HTTP' => 'http',
            'Haml' => 'haml',
            'Handlebars' => 'handlebars',
            'Haskell' => 'haskell',
            'Haxe' => 'haxe',
            'Hy' => 'hy',
            'Ini, TOML' => 'ini',
            'Inform7' => 'inform7',
            'IRPF90' => 'irpf90',
            'JSON' => 'json',
            'Java' => 'java',
            'JavaScript' => 'javascript',
            'Jolie' => 'jolie',
            'Julia' => 'julia',
            'Kotlin' => 'kotlin',
            'LaTeX' => 'tex',
            'Leaf' => 'leaf',
            'Lean' => 'lean',
            'Lasso' => 'lasso',
            'Less' => 'less',
            'LDIF' => 'ldif',
            'Lisp' => 'lisp',
            'LiveScript' => 'livescript',
            'Lua' => 'lua',
            'Macaulay2' => 'macaulay2',
            'Makefile' => 'makefile',
            'Markdown' => 'markdown',
            'Mathematica' => 'mathematica',
            'Matlab' => 'matlab',
            'Maxima' => 'maxima',
            'Mercury' => 'mercury',
            'Mizar' => 'mizar',
            'MKB' => 'mkb',
            'Mojolicious' => 'mojolicious',
            'Monkey' => 'monkey',
            'Moonscript' => 'moonscript',
            'N1QL' => 'n1ql',
            'NSIS' => 'nsis',
            'Never' => 'never',
            'Nginx' => 'nginx',
            'Nim' => 'nim',
            'Nix' => 'nix',
            'Oak' => 'oak',
            'OCaml' => 'ocaml',
            'OpenSCAD' => 'openscad',
            'Oxygene' => 'oxygene',
            'PF' => 'pf',
            'PHP' => 'php',
            'Papyrus' => 'papyrus',
            'Parser3' => 'parser3',
            'Perl' => 'perl',
            'Pine Script' => 'pine',
            'Plaintext' => 'plaintext',
            'Pony' => 'pony',
            'PowerShell' => 'powershell',
            'Processing' => 'processing',
            'Prolog' => 'prolog',
            'Properties' => 'properties',
            'Puppet' => 'puppet',
            'Python' => 'python',
            'Q#' => 'qsharp',
            'Q' => 'k',
            'QML' => 'qml',
            'R' => 'r',
            'ReasonML' => 'reasonml',
            'RiScript' => 'risc',
            'Roboconf' => 'graph',
            'Ruby' => 'ruby',
            'Rust' => 'rust',
            'SAS' => 'SAS',
            'SCSS' => 'scss',
            'SQL' => 'sql',
            'Scala' => 'scala',
            'Scheme' => 'scheme',
            'Scilab' => 'scilab',
            'Shell' => 'shell',
            'Smali' => 'smali',
            'Smalltalk' => 'smalltalk',
            'SML' => 'sml',
            'Solidity' => 'solidity',
            'Splunk SPL' => 'spl',
            'Stan' => 'stan',
            'Stata' => 'stata',
            'Stylus' => 'stylus',
            'SubUnit' => 'subunit',
            'Supercollider' => 'supercollider',
            'Svelte' => 'svelte',
            'Swift' => 'swift',
            'Tcl' => 'tcl',
            'Thrift' => 'thrift',
            'TP' => 'tp',
            'Transact-SQL' => 'tsql',
            'Twig' => 'twig',
            'TypeScript' => 'typescript',
            'VB.Net' => 'vbnet',
            'VBA' => 'vba',
            'VBScript' => 'vbscript',
            'VHDL' => 'vhdl',
            'Vala' => 'vala',
            'Verilog' => 'verilog',
            'Vim Script' => 'vim',
            'X#' => 'xsharp',
            'X++' => 'axapta',
            'XL' => 'xl',
            'XQuery' => 'xquery',
            'YAML' => 'yml',
        ];

        $insert = [];

        foreach ($langs as $lang => $value) {
            $insert[] = [
                'hash' => bin2hex(random_bytes(20)),
                'name' => $lang,
                'key' => $value
            ];
        }

        Lang::insert($insert);
    }
}
